steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build',
      '-t',
      'us-central1-docker.pkg.dev/kubernetesassignment-417521/kubernetes-assignment/container-2:latest',
      '-f',
      'Dockerfile.container2', 
      '.',
    ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/kubernetesassignment-417521/kubernetes-assignment/container-2:latest']
 
images:
- 'us-central1-docker.pkg.dev/kubernetesassignment-417521/kubernetes-assignment/container-2:latest'